print(" ooooooooooooooooo")                                                       
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ") 
print(" *** ")
print("*   *")
print(" *   ")
print("  *  ")
print("*  * ")
print("*   *")
print(" *** ")
