print(" *** ")
print("*   *")
print("*****")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print(" **** ")
print("*    *")
print("*     ")
print("*  ***")
print("*    *")
print("*    *")
print(" **** ")
print("     ")
print("     ")
print("     ")
print("*   *")
print("** **")
print("* * *")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print(" *** ")
print("*   *")
print(" *   ")
print("  *  ")
print("*  * ")
print("*   *")
print(" *** ")


print(" ooooooooooooooooo")                                                       
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ") 

