print(" *** ")
print("*   *")
print("*****")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print(" **** ")
print("*    *")
print("*     ")
print("*  ***")
print("*    *")
print("*    *")
print(" **** ")
print("     ")
print("     ")
print("     ")
print("*   *")
print("** **")
print("* * *")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print(" *** ")
print("*   *")
print(" *   ")
print("  *  ")
print("*  * ")
print("*   *")
print(" *** ")


print(" ooooooooooooooooo")                                                       
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ") 




print("              ___.-~\"~-._   __....__")
print("            .'    `    \ ~\"~        ``-.")
print("           /` _      )  `\              `\\")
print("          /`  a)    /     |               `\\")
print("         :`        /      |                 \\")
print("    <`-._|`  .-.  (      /   .            `;\\")
print("     `-. `--'_.'-.;\___/'   .      .       | \\")
print("  _     /:--`     |        /     /        .'  \\")
print(" \"\   /`/        |       '     '         /    :`;")
print(" `\'\_/`/         .\     /`~`=-.:        /     ``")
print("   `._.'          /`\    |      `\      /(")
print("                 /  /\   |        `Y   /  \\")
print("                J  /  Y  |         |  /`\  \\")
print("               /  |   |  |         |  |  |  |")
print("              \"---\"  /___|        /___|  /__|")
print("                     \"'''         '\"\"\"  '\"\"\"")

