print(" *** ")
print("*   *")
print("*****")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print("     ")
print(" **** ")
print("*    *")
print("*     ")
print("*  ***")
print("*    *")
print("*    *")
print(" **** ")
print("     ")
print("     ")
print("     ")
print("*   *")
print("** **")
print("* * *")
print("*   *")
print("*   *")
print("*   *")
print("     ")
print("     ")
print("     ")
print(" *** ")
print("*   *")
print(" *   ")
print("  *  ")
print("*  * ")
print("*   *")
print(" *** ")


print(" ooooooooooooooooo")                                                       
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("oooo              ")                                                      
print("ooooooooooooooooo ")                                                       
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("             oooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ")                                                        
print("ooooooooooooooooo ") 


print("   _       _        ")                 
print("  (_)     | |       ")
print("   _  ___ | | _____ ")
print("  | |/ _ \| |/ / _ \")
print("  | | (_) |   <  __/")
print("  | |\___/|_|\_\___|")
print(" _/ |               ")
print("|__/                ")

